export const structure={
    name:'src',
    isFolder:true,
    files:[
        {
            name:'Hooks',
            isFolder:true,
            files:[
                {
                    name:'useState.js',
                    isFolder:false
                },
                {
                    name:'useEffect.js',
                    isFolder:false
                },
            ],
        },
        {
            name:'App.jsx',
            isFolder:false
        },
        {
            name:'Components',
            isFolder:true,
            files:[
                {
                    name:'Popup.jsx',
                    isFolder:false
                },
                {
                    name:'Button.js',
                    isFolder:false
                },
            ],
        }
    ]
}